export const FlowTestData = {
  Edge: [
    {
      animated: true,
      id: "0-1",
      source: "ManagedElement",
      target: "GnbDuFunction",
      type: "step",
    },
    {
      animated: true,
      id: "0-2",
      source: "ManagedElement",
      target: "GnbCuCpFunction",
      type: "step",
    },
    {
      animated: true,
      id: "0-3",
      source: "ManagedElement",
      target: "GnbCuUpFunction",
      type: "step",
    },
    {
      animated: true,
      id: "1-1",
      source: "GnbDuFunction",
      target: "GnbDuFunction-1",
      type: "step",
    },
    {
      animated: true,
      id: "1-1-1",
      source: "GnbDuFunction-1",
      target: "1-MaxTxPower",
      type: "step",
    },
    {
      animated: true,
      id: "1-1-2",
      source: "GnbDuFunction-1",
      target: "2-MaxTxPower",
      type: "step",
    },
    {
      animated: true,
      id: "1-1-3",
      source: "GnbDuFunction-1",
      target: "3-MaxTxPower",
      type: "step",
    },
    {
      animated: true,
      id: "1-1-4",
      source: "GnbDuFunction-1",
      target: "4-MaxTxPower",
      type: "step",
    },
    {
      animated: true,
      id: "1-1-5",
      source: "GnbDuFunction-1",
      target: "5-MaxTxPower",
      type: "step",
    },
    {
      animated: true,
      id: "1-1-6",
      source: "GnbDuFunction-1",
      target: "6-MaxTxPower",
      type: "step",
    },
    {
      animated: true,
      id: "1-1-7",
      source: "GnbDuFunction-1",
      target: "7-MaxTxPower",
      type: "step",
    },
    {
      animated: true,
      id: "1-1-8",
      source: "GnbDuFunction-1",
      target: "8-MaxTxPower",
      type: "step",
    },
    {
      animated: true,
      id: "1-2",
      source: "GnbDuFunction",
      target: "GnbDuFunction-2",
      type: "step",
    },
    {
      animated: true,
      id: "1-2-9",
      source: "GnbDuFunction-2",
      target: "9-MaxTxPower",
      type: "step",
    },
    {
      animated: true,
      id: "1-2-10",
      source: "GnbDuFunction-2",
      target: "10-MaxTxPower",
      type: "step",
    },
    {
      animated: true,
      id: "1-2-11",
      source: "GnbDuFunction-2",
      target: "11-MaxTxPower",
      type: "step",
    },
    {
      animated: true,
      id: "1-2-12",
      source: "GnbDuFunction-2",
      target: "12-MaxTxPower",
      type: "step",
    },
    {
      animated: true,
      id: "1-2-13",
      source: "GnbDuFunction-2",
      target: "13-MaxTxPower",
      type: "step",
    },
    {
      animated: true,
      id: "1-2-14",
      source: "GnbDuFunction-2",
      target: "14-MaxTxPower",
      type: "step",
    },
    {
      animated: true,
      id: "1-2-15",
      source: "GnbDuFunction-2",
      target: "15-MaxTxPower",
      type: "step",
    },
    {
      animated: true,
      id: "1-2-16",
      source: "GnbDuFunction-2",
      target: "16-MaxTxPower",
      type: "step",
    },
    {
      animated: true,
      id: "1-2-17",
      source: "GnbDuFunction-2",
      target: "17-MaxTxPower",
      type: "step",
    },
    {
      animated: true,
      id: "1-3",
      source: "GnbDuFunction",
      target: "GnbDuFunction-3",
      type: "step",
    },
    {
      animated: true,
      id: "1-3-18",
      source: "GnbDuFunction-3",
      target: "18-MaxTxPower",
      type: "step",
    },
    {
      animated: true,
      id: "1-3-19",
      source: "GnbDuFunction-3",
      target: "19-MaxTxPower",
      type: "step",
    },
    {
      animated: true,
      id: "1-3-20",
      source: "GnbDuFunction-3",
      target: "20-MaxTxPower",
      type: "step",
    },
    {
      animated: true,
      id: "1-3-21",
      source: "GnbDuFunction-3",
      target: "21-MaxTxPower",
      type: "step",
    },
    {
      animated: true,
      id: "1-3-22",
      source: "GnbDuFunction-3",
      target: "22-MaxTxPower",
      type: "step",
    },
    {
      animated: true,
      id: "1-3-23",
      source: "GnbDuFunction-3",
      target: "23-MaxTxPower",
      type: "step",
    },
    {
      animated: true,
      id: "1-3-24",
      source: "GnbDuFunction-3",
      target: "24-MaxTxPower",
      type: "step",
    },
    {
      animated: true,
      id: "1-3-25",
      source: "GnbDuFunction-3",
      target: "25-MaxTxPower",
      type: "step",
    },
    {
      animated: true,
      id: "1-3-26",
      source: "GnbDuFunction-3",
      target: "26-MaxTxPower",
      type: "step",
    },
    {
      animated: true,
      id: "2-1",
      source: "GnbCuCpFunction",
      target: "GnbCuCpFunction-1",
      type: "step",
    },
    {
      animated: true,
      id: "2-1-1",
      source: "GnbCuCpFunction-1",
      target: "1-isEnergySaving",
      type: "step",
    },
    {
      animated: true,
      id: "2-2",
      source: "GnbCuCpFunction",
      target: "GnbCuCpFunction-2",
      type: "step",
    },
    {
      animated: true,
      id: "2-2-2",
      source: "GnbCuCpFunction-2",
      target: "2-isEnergySaving",
      type: "step",
    },
    {
      animated: true,
      id: "2-3",
      source: "GnbCuCpFunction",
      target: "GnbCuCpFunction-3",
      type: "step",
    },
    {
      animated: true,
      id: "2-3-3",
      source: "GnbCuCpFunction-3",
      target: "3-isEnergySaving",
      type: "step",
    },
    {
      animated: true,
      id: "2-4",
      source: "GnbCuCpFunction",
      target: "GnbCuCpFunction-4",
      type: "step",
    },
    {
      animated: true,
      id: "2-4-4",
      source: "GnbCuCpFunction-4",
      target: "4-isEnergySaving",
      type: "step",
    },
    {
      animated: true,
      id: "2-5",
      source: "GnbCuCpFunction",
      target: "GnbCuCpFunction-5",
      type: "step",
    },
    {
      animated: true,
      id: "2-5-5",
      source: "GnbCuCpFunction-5",
      target: "5-isEnergySaving",
      type: "step",
    },
    {
      animated: true,
      id: "2-6",
      source: "GnbCuCpFunction",
      target: "GnbCuCpFunction-6",
      type: "step",
    },
    {
      animated: true,
      id: "2-6-6",
      source: "GnbCuCpFunction-6",
      target: "6-isEnergySaving",
      type: "step",
    },
    {
      animated: true,
      id: "2-7",
      source: "GnbCuCpFunction",
      target: "GnbCuCpFunction-7",
      type: "step",
    },
    {
      animated: true,
      id: "2-7-7",
      source: "GnbCuCpFunction-7",
      target: "7-isEnergySaving",
      type: "step",
    },
    {
      animated: true,
      id: "2-8",
      source: "GnbCuCpFunction",
      target: "GnbCuCpFunction-8",
      type: "step",
    },
    {
      animated: true,
      id: "2-8-8",
      source: "GnbCuCpFunction-8",
      target: "8-isEnergySaving",
      type: "step",
    },
    {
      animated: true,
      id: "2-9",
      source: "GnbCuCpFunction",
      target: "GnbCuCpFunction-9",
      type: "step",
    },
    {
      animated: true,
      id: "2-9-9",
      source: "GnbCuCpFunction-9",
      target: "9-isEnergySaving",
      type: "step",
    },
    {
      animated: true,
      id: "2-10",
      source: "GnbCuCpFunction",
      target: "GnbCuCpFunction-10",
      type: "step",
    },
    {
      animated: true,
      id: "2-10-10",
      source: "GnbCuCpFunction-10",
      target: "10-isEnergySaving",
      type: "step",
    },
    {
      animated: true,
      id: "2-11",
      source: "GnbCuCpFunction",
      target: "GnbCuCpFunction-11",
      type: "step",
    },
    {
      animated: true,
      id: "2-11-11",
      source: "GnbCuCpFunction-11",
      target: "11-isEnergySaving",
      type: "step",
    },
    {
      animated: true,
      id: "2-12",
      source: "GnbCuCpFunction",
      target: "GnbCuCpFunction-12",
      type: "step",
    },
    {
      animated: true,
      id: "2-12-12",
      source: "GnbCuCpFunction-12",
      target: "12-isEnergySaving",
      type: "step",
    },
    {
      animated: true,
      id: "2-13",
      source: "GnbCuCpFunction",
      target: "GnbCuCpFunction-13",
      type: "step",
    },
    {
      animated: true,
      id: "2-13-13",
      source: "GnbCuCpFunction-13",
      target: "13-isEnergySaving",
      type: "step",
    },
    {
      animated: true,
      id: "2-14",
      source: "GnbCuCpFunction",
      target: "GnbCuCpFunction-14",
      type: "step",
    },
    {
      animated: true,
      id: "2-14-14",
      source: "GnbCuCpFunction-14",
      target: "14-isEnergySaving",
      type: "step",
    },
    {
      animated: true,
      id: "2-15",
      source: "GnbCuCpFunction",
      target: "GnbCuCpFunction-15",
      type: "step",
    },
    {
      animated: true,
      id: "2-15-15",
      source: "GnbCuCpFunction-15",
      target: "15-isEnergySaving",
      type: "step",
    },
    {
      animated: true,
      id: "2-16",
      source: "GnbCuCpFunction",
      target: "GnbCuCpFunction-16",
      type: "step",
    },
    {
      animated: true,
      id: "2-16-16",
      source: "GnbCuCpFunction-16",
      target: "16-isEnergySaving",
      type: "step",
    },
    {
      animated: true,
      id: "2-17",
      source: "GnbCuCpFunction",
      target: "GnbCuCpFunction-17",
      type: "step",
    },
    {
      animated: true,
      id: "2-17-17",
      source: "GnbCuCpFunction-17",
      target: "17-isEnergySaving",
      type: "step",
    },
    {
      animated: true,
      id: "2-18",
      source: "GnbCuCpFunction",
      target: "GnbCuCpFunction-18",
      type: "step",
    },
    {
      animated: true,
      id: "2-18-18",
      source: "GnbCuCpFunction-18",
      target: "18-isEnergySaving",
      type: "step",
    },
    {
      animated: true,
      id: "2-19",
      source: "GnbCuCpFunction",
      target: "GnbCuCpFunction-19",
      type: "step",
    },
    {
      animated: true,
      id: "2-19-19",
      source: "GnbCuCpFunction-19",
      target: "19-isEnergySaving",
      type: "step",
    },
    {
      animated: true,
      id: "2-20",
      source: "GnbCuCpFunction",
      target: "GnbCuCpFunction-20",
      type: "step",
    },
    {
      animated: true,
      id: "2-20-20",
      source: "GnbCuCpFunction-20",
      target: "20-isEnergySaving",
      type: "step",
    },
    {
      animated: true,
      id: "2-21",
      source: "GnbCuCpFunction",
      target: "GnbCuCpFunction-21",
      type: "step",
    },
    {
      animated: true,
      id: "2-21-21",
      source: "GnbCuCpFunction-21",
      target: "21-isEnergySaving",
      type: "step",
    },
    {
      animated: true,
      id: "2-22",
      source: "GnbCuCpFunction",
      target: "GnbCuCpFunction-22",
      type: "step",
    },
    {
      animated: true,
      id: "2-22-22",
      source: "GnbCuCpFunction-22",
      target: "22-isEnergySaving",
      type: "step",
    },
    {
      animated: true,
      id: "2-23",
      source: "GnbCuCpFunction",
      target: "GnbCuCpFunction-23",
      type: "step",
    },
    {
      animated: true,
      id: "2-23-23",
      source: "GnbCuCpFunction-23",
      target: "23-isEnergySaving",
      type: "step",
    },
    {
      animated: true,
      id: "2-24",
      source: "GnbCuCpFunction",
      target: "GnbCuCpFunction-24",
      type: "step",
    },
    {
      animated: true,
      id: "2-24-24",
      source: "GnbCuCpFunction-24",
      target: "24-isEnergySaving",
      type: "step",
    },
    {
      animated: true,
      id: "2-25",
      source: "GnbCuCpFunction",
      target: "GnbCuCpFunction-25",
      type: "step",
    },
    {
      animated: true,
      id: "2-25-25",
      source: "GnbCuCpFunction-25",
      target: "25-isEnergySaving",
      type: "step",
    },
    {
      animated: true,
      id: "2-26",
      source: "GnbCuCpFunction",
      target: "GnbCuCpFunction-26",
      type: "step",
    },
    {
      animated: true,
      id: "2-26-26",
      source: "GnbCuCpFunction-26",
      target: "26-isEnergySaving",
      type: "step",
    },
    {
      animated: true,
      id: "3-1",
      source: "GnbCuUpFunction",
      target: "GnbCuUpFunction-1",
      type: "step",
    },
  ],
  Node: [
    {
      data: { label: "ManagedElement", type: "input" },
      id: "ManagedElement",
      position: { x: 0, y: 0 },
      sourcePosition: "Position.Right",
      type: "customNodeType",
    },
    {
      data: { label: "GnbDuFunction" },
      id: "GnbDuFunction",
      position: { x: 200, y: 0 },
      sourcePosition: "Position.Right",
      targetPosition: "Position.Left",
      type: "customNodeType",
    },
    {
      data: { label: "GnbCuCpFunction" },
      id: "GnbCuCpFunction",
      position: { x: 200, y: 1000 },
      sourcePosition: "Position.Right",
      targetPosition: "Position.Left",
      type: "customNodeType",
    },
    {
      data: { label: "GnbCuUpFunction" },
      id: "GnbCuUpFunction",
      position: { x: 200, y: 2000 },
      sourcePosition: "Position.Right",
      targetPosition: "Position.Left",
      type: "customNodeType",
    },
    {
      data: { label: "GnbDuFunction-1" },
      id: "GnbDuFunction-1",
      position: { x: 400, y: 0 },
      sourcePosition: "Position.Right",
      targetPosition: "Position.Left",
      type: "customNodeType",
    },
    {
      data: { label: "1-MaxTxPower", value: 40 },
      id: "1-MaxTxPower",
      position: { x: 600, y: 0 },
      targetPosition: "Position.Left",
      type: "valueNodeType",
    },
    {
      data: { label: "2-MaxTxPower", value: 40 },
      id: "2-MaxTxPower",
      position: { x: 600, y: 50 },
      targetPosition: "Position.Left",
      type: "valueNodeType",
    },
    {
      data: { label: "3-MaxTxPower", value: 40 },
      id: "3-MaxTxPower",
      position: { x: 600, y: 100 },
      targetPosition: "Position.Left",
      type: "valueNodeType",
    },
    {
      data: { label: "4-MaxTxPower", value: 40 },
      id: "4-MaxTxPower",
      position: { x: 600, y: 150 },
      targetPosition: "Position.Left",
      type: "valueNodeType",
    },
    {
      data: { label: "5-MaxTxPower", value: 40 },
      id: "5-MaxTxPower",
      position: { x: 600, y: 200 },
      targetPosition: "Position.Left",
      type: "valueNodeType",
    },
    {
      data: { label: "6-MaxTxPower", value: 40 },
      id: "6-MaxTxPower",
      position: { x: 600, y: 250 },
      targetPosition: "Position.Left",
      type: "valueNodeType",
    },
    {
      data: { label: "7-MaxTxPower", value: 40 },
      id: "7-MaxTxPower",
      position: { x: 600, y: 300 },
      targetPosition: "Position.Left",
      type: "valueNodeType",
    },
    {
      data: { label: "8-MaxTxPower", value: 40 },
      id: "8-MaxTxPower",
      position: { x: 600, y: 350 },
      targetPosition: "Position.Left",
      type: "valueNodeType",
    },
    {
      data: { label: "GnbDuFunction-2" },
      id: "GnbDuFunction-2",
      position: { x: 400, y: 400 },
      sourcePosition: "Position.Right",
      targetPosition: "Position.Left",
      type: "customNodeType",
    },
    {
      data: { label: "9-MaxTxPower", value: 40 },
      id: "9-MaxTxPower",
      position: { x: 600, y: 400 },
      targetPosition: "Position.Left",
      type: "valueNodeType",
    },
    {
      data: { label: "10-MaxTxPower", value: 40 },
      id: "10-MaxTxPower",
      position: { x: 600, y: 450 },
      targetPosition: "Position.Left",
      type: "valueNodeType",
    },
    {
      data: { label: "11-MaxTxPower", value: 40 },
      id: "11-MaxTxPower",
      position: { x: 600, y: 500 },
      targetPosition: "Position.Left",
      type: "valueNodeType",
    },
    {
      data: { label: "12-MaxTxPower", value: 40 },
      id: "12-MaxTxPower",
      position: { x: 600, y: 550 },
      targetPosition: "Position.Left",
      type: "valueNodeType",
    },
    {
      data: { label: "13-MaxTxPower", value: 40 },
      id: "13-MaxTxPower",
      position: { x: 600, y: 600 },
      targetPosition: "Position.Left",
      type: "valueNodeType",
    },
    {
      data: { label: "14-MaxTxPower", value: 40 },
      id: "14-MaxTxPower",
      position: { x: 600, y: 650 },
      targetPosition: "Position.Left",
      type: "valueNodeType",
    },
    {
      data: { label: "15-MaxTxPower", value: 40 },
      id: "15-MaxTxPower",
      position: { x: 600, y: 700 },
      targetPosition: "Position.Left",
      type: "valueNodeType",
    },
    {
      data: { label: "16-MaxTxPower", value: 40 },
      id: "16-MaxTxPower",
      position: { x: 600, y: 750 },
      targetPosition: "Position.Left",
      type: "valueNodeType",
    },
    {
      data: { label: "17-MaxTxPower", value: 40 },
      id: "17-MaxTxPower",
      position: { x: 600, y: 800 },
      targetPosition: "Position.Left",
      type: "valueNodeType",
    },
    {
      data: { label: "GnbDuFunction-3" },
      id: "GnbDuFunction-3",
      position: { x: 400, y: 850 },
      sourcePosition: "Position.Right",
      targetPosition: "Position.Left",
      type: "customNodeType",
    },
    {
      data: { label: "18-MaxTxPower", value: 40 },
      id: "18-MaxTxPower",
      position: { x: 600, y: 850 },
      targetPosition: "Position.Left",
      type: "valueNodeType",
    },
    {
      data: { label: "19-MaxTxPower", value: 40 },
      id: "19-MaxTxPower",
      position: { x: 600, y: 900 },
      targetPosition: "Position.Left",
      type: "valueNodeType",
    },
    {
      data: { label: "20-MaxTxPower", value: 40 },
      id: "20-MaxTxPower",
      position: { x: 600, y: 950 },
      targetPosition: "Position.Left",
      type: "valueNodeType",
    },
    {
      data: { label: "21-MaxTxPower", value: 40 },
      id: "21-MaxTxPower",
      position: { x: 600, y: 1000 },
      targetPosition: "Position.Left",
      type: "valueNodeType",
    },
    {
      data: { label: "22-MaxTxPower", value: 40 },
      id: "22-MaxTxPower",
      position: { x: 600, y: 1050 },
      targetPosition: "Position.Left",
      type: "valueNodeType",
    },
    {
      data: { label: "23-MaxTxPower", value: 40 },
      id: "23-MaxTxPower",
      position: { x: 600, y: 1100 },
      targetPosition: "Position.Left",
      type: "valueNodeType",
    },
    {
      data: { label: "24-MaxTxPower", value: 40 },
      id: "24-MaxTxPower",
      position: { x: 600, y: 1150 },
      targetPosition: "Position.Left",
      type: "valueNodeType",
    },
    {
      data: { label: "25-MaxTxPower", value: 40 },
      id: "25-MaxTxPower",
      position: { x: 600, y: 1200 },
      targetPosition: "Position.Left",
      type: "valueNodeType",
    },
    {
      data: { label: "26-MaxTxPower", value: 40 },
      id: "26-MaxTxPower",
      position: { x: 600, y: 1250 },
      targetPosition: "Position.Left",
      type: "valueNodeType",
    },
    {
      data: { label: "GnbCuCpFunction-1" },
      id: "GnbCuCpFunction-1",
      position: { x: 400, y: 1300 },
      sourcePosition: "Position.Right",
      targetPosition: "Position.Left",
      type: "customNodeType",
    },
    {
      data: { label: "1-isEnergySaving", state: "OFF" },
      id: "1-isEnergySaving",
      position: { x: 600, y: 1300 },
      targetPosition: "Position.Left",
      type: "stateNodeType",
    },
    {
      data: { label: "GnbCuCpFunction-2" },
      id: "GnbCuCpFunction-2",
      position: { x: 400, y: 1350 },
      sourcePosition: "Position.Right",
      targetPosition: "Position.Left",
      type: "customNodeType",
    },
    {
      data: { label: "2-isEnergySaving", state: "OFF" },
      id: "2-isEnergySaving",
      position: { x: 600, y: 1350 },
      targetPosition: "Position.Left",
      type: "stateNodeType",
    },
    {
      data: { label: "GnbCuCpFunction-3" },
      id: "GnbCuCpFunction-3",
      position: { x: 400, y: 1400 },
      sourcePosition: "Position.Right",
      targetPosition: "Position.Left",
      type: "customNodeType",
    },
    {
      data: { label: "3-isEnergySaving", state: "OFF" },
      id: "3-isEnergySaving",
      position: { x: 600, y: 1400 },
      targetPosition: "Position.Left",
      type: "stateNodeType",
    },
    {
      data: { label: "GnbCuCpFunction-4" },
      id: "GnbCuCpFunction-4",
      position: { x: 400, y: 1450 },
      sourcePosition: "Position.Right",
      targetPosition: "Position.Left",
      type: "customNodeType",
    },
    {
      data: { label: "4-isEnergySaving", state: "OFF" },
      id: "4-isEnergySaving",
      position: { x: 600, y: 1450 },
      targetPosition: "Position.Left",
      type: "stateNodeType",
    },
    {
      data: { label: "GnbCuCpFunction-5" },
      id: "GnbCuCpFunction-5",
      position: { x: 400, y: 1500 },
      sourcePosition: "Position.Right",
      targetPosition: "Position.Left",
      type: "customNodeType",
    },
    {
      data: { label: "5-isEnergySaving", state: "OFF" },
      id: "5-isEnergySaving",
      position: { x: 600, y: 1500 },
      targetPosition: "Position.Left",
      type: "stateNodeType",
    },
    {
      data: { label: "GnbCuCpFunction-6" },
      id: "GnbCuCpFunction-6",
      position: { x: 400, y: 1550 },
      sourcePosition: "Position.Right",
      targetPosition: "Position.Left",
      type: "customNodeType",
    },
    {
      data: { label: "6-isEnergySaving", state: "OFF" },
      id: "6-isEnergySaving",
      position: { x: 600, y: 1550 },
      targetPosition: "Position.Left",
      type: "stateNodeType",
    },
    {
      data: { label: "GnbCuCpFunction-7" },
      id: "GnbCuCpFunction-7",
      position: { x: 400, y: 1600 },
      sourcePosition: "Position.Right",
      targetPosition: "Position.Left",
      type: "customNodeType",
    },
    {
      data: { label: "7-isEnergySaving", state: "OFF" },
      id: "7-isEnergySaving",
      position: { x: 600, y: 1600 },
      targetPosition: "Position.Left",
      type: "stateNodeType",
    },
    {
      data: { label: "GnbCuCpFunction-8" },
      id: "GnbCuCpFunction-8",
      position: { x: 400, y: 1650 },
      sourcePosition: "Position.Right",
      targetPosition: "Position.Left",
      type: "customNodeType",
    },
    {
      data: { label: "8-isEnergySaving", state: "OFF" },
      id: "8-isEnergySaving",
      position: { x: 600, y: 1650 },
      targetPosition: "Position.Left",
      type: "stateNodeType",
    },
    {
      data: { label: "GnbCuCpFunction-9" },
      id: "GnbCuCpFunction-9",
      position: { x: 400, y: 1700 },
      sourcePosition: "Position.Right",
      targetPosition: "Position.Left",
      type: "customNodeType",
    },
    {
      data: { label: "9-isEnergySaving", state: "OFF" },
      id: "9-isEnergySaving",
      position: { x: 600, y: 1700 },
      targetPosition: "Position.Left",
      type: "stateNodeType",
    },
    {
      data: { label: "GnbCuCpFunction-10" },
      id: "GnbCuCpFunction-10",
      position: { x: 400, y: 1750 },
      sourcePosition: "Position.Right",
      targetPosition: "Position.Left",
      type: "customNodeType",
    },
    {
      data: { label: "10-isEnergySaving", state: "OFF" },
      id: "10-isEnergySaving",
      position: { x: 600, y: 1750 },
      targetPosition: "Position.Left",
      type: "stateNodeType",
    },
    {
      data: { label: "GnbCuCpFunction-11" },
      id: "GnbCuCpFunction-11",
      position: { x: 400, y: 1800 },
      sourcePosition: "Position.Right",
      targetPosition: "Position.Left",
      type: "customNodeType",
    },
    {
      data: { label: "11-isEnergySaving", state: "OFF" },
      id: "11-isEnergySaving",
      position: { x: 600, y: 1800 },
      targetPosition: "Position.Left",
      type: "stateNodeType",
    },
    {
      data: { label: "GnbCuCpFunction-12" },
      id: "GnbCuCpFunction-12",
      position: { x: 400, y: 1850 },
      sourcePosition: "Position.Right",
      targetPosition: "Position.Left",
      type: "customNodeType",
    },
    {
      data: { label: "12-isEnergySaving", state: "OFF" },
      id: "12-isEnergySaving",
      position: { x: 600, y: 1850 },
      targetPosition: "Position.Left",
      type: "stateNodeType",
    },
    {
      data: { label: "GnbCuCpFunction-13" },
      id: "GnbCuCpFunction-13",
      position: { x: 400, y: 1900 },
      sourcePosition: "Position.Right",
      targetPosition: "Position.Left",
      type: "customNodeType",
    },
    {
      data: { label: "13-isEnergySaving", state: "OFF" },
      id: "13-isEnergySaving",
      position: { x: 600, y: 1900 },
      targetPosition: "Position.Left",
      type: "stateNodeType",
    },
    {
      data: { label: "GnbCuCpFunction-14" },
      id: "GnbCuCpFunction-14",
      position: { x: 400, y: 1950 },
      sourcePosition: "Position.Right",
      targetPosition: "Position.Left",
      type: "customNodeType",
    },
    {
      data: { label: "14-isEnergySaving", state: "OFF" },
      id: "14-isEnergySaving",
      position: { x: 600, y: 1950 },
      targetPosition: "Position.Left",
      type: "stateNodeType",
    },
    {
      data: { label: "GnbCuCpFunction-15" },
      id: "GnbCuCpFunction-15",
      position: { x: 400, y: 2000 },
      sourcePosition: "Position.Right",
      targetPosition: "Position.Left",
      type: "customNodeType",
    },
    {
      data: { label: "15-isEnergySaving", state: "OFF" },
      id: "15-isEnergySaving",
      position: { x: 600, y: 2000 },
      targetPosition: "Position.Left",
      type: "stateNodeType",
    },
    {
      data: { label: "GnbCuCpFunction-16" },
      id: "GnbCuCpFunction-16",
      position: { x: 400, y: 2050 },
      sourcePosition: "Position.Right",
      targetPosition: "Position.Left",
      type: "customNodeType",
    },
    {
      data: { label: "16-isEnergySaving", state: "OFF" },
      id: "16-isEnergySaving",
      position: { x: 600, y: 2050 },
      targetPosition: "Position.Left",
      type: "stateNodeType",
    },
    {
      data: { label: "GnbCuCpFunction-17" },
      id: "GnbCuCpFunction-17",
      position: { x: 400, y: 2100 },
      sourcePosition: "Position.Right",
      targetPosition: "Position.Left",
      type: "customNodeType",
    },
    {
      data: { label: "17-isEnergySaving", state: "OFF" },
      id: "17-isEnergySaving",
      position: { x: 600, y: 2100 },
      targetPosition: "Position.Left",
      type: "stateNodeType",
    },
    {
      data: { label: "GnbCuCpFunction-18" },
      id: "GnbCuCpFunction-18",
      position: { x: 400, y: 2150 },
      sourcePosition: "Position.Right",
      targetPosition: "Position.Left",
      type: "customNodeType",
    },
    {
      data: { label: "18-isEnergySaving", state: "OFF" },
      id: "18-isEnergySaving",
      position: { x: 600, y: 2150 },
      targetPosition: "Position.Left",
      type: "stateNodeType",
    },
    {
      data: { label: "GnbCuCpFunction-19" },
      id: "GnbCuCpFunction-19",
      position: { x: 400, y: 2200 },
      sourcePosition: "Position.Right",
      targetPosition: "Position.Left",
      type: "customNodeType",
    },
    {
      data: { label: "19-isEnergySaving", state: "OFF" },
      id: "19-isEnergySaving",
      position: { x: 600, y: 2200 },
      targetPosition: "Position.Left",
      type: "stateNodeType",
    },
    {
      data: { label: "GnbCuCpFunction-20" },
      id: "GnbCuCpFunction-20",
      position: { x: 400, y: 2250 },
      sourcePosition: "Position.Right",
      targetPosition: "Position.Left",
      type: "customNodeType",
    },
    {
      data: { label: "20-isEnergySaving", state: "OFF" },
      id: "20-isEnergySaving",
      position: { x: 600, y: 2250 },
      targetPosition: "Position.Left",
      type: "stateNodeType",
    },
    {
      data: { label: "GnbCuCpFunction-21" },
      id: "GnbCuCpFunction-21",
      position: { x: 400, y: 2300 },
      sourcePosition: "Position.Right",
      targetPosition: "Position.Left",
      type: "customNodeType",
    },
    {
      data: { label: "21-isEnergySaving", state: "OFF" },
      id: "21-isEnergySaving",
      position: { x: 600, y: 2300 },
      targetPosition: "Position.Left",
      type: "stateNodeType",
    },
    {
      data: { label: "GnbCuCpFunction-22" },
      id: "GnbCuCpFunction-22",
      position: { x: 400, y: 2350 },
      sourcePosition: "Position.Right",
      targetPosition: "Position.Left",
      type: "customNodeType",
    },
    {
      data: { label: "22-isEnergySaving", state: "OFF" },
      id: "22-isEnergySaving",
      position: { x: 600, y: 2350 },
      targetPosition: "Position.Left",
      type: "stateNodeType",
    },
    {
      data: { label: "GnbCuCpFunction-23" },
      id: "GnbCuCpFunction-23",
      position: { x: 400, y: 2400 },
      sourcePosition: "Position.Right",
      targetPosition: "Position.Left",
      type: "customNodeType",
    },
    {
      data: { label: "23-isEnergySaving", state: "OFF" },
      id: "23-isEnergySaving",
      position: { x: 600, y: 2400 },
      targetPosition: "Position.Left",
      type: "stateNodeType",
    },
    {
      data: { label: "GnbCuCpFunction-24" },
      id: "GnbCuCpFunction-24",
      position: { x: 400, y: 2450 },
      sourcePosition: "Position.Right",
      targetPosition: "Position.Left",
      type: "customNodeType",
    },
    {
      data: { label: "24-isEnergySaving", state: "OFF" },
      id: "24-isEnergySaving",
      position: { x: 600, y: 2450 },
      targetPosition: "Position.Left",
      type: "stateNodeType",
    },
    {
      data: { label: "GnbCuCpFunction-25" },
      id: "GnbCuCpFunction-25",
      position: { x: 400, y: 2500 },
      sourcePosition: "Position.Right",
      targetPosition: "Position.Left",
      type: "customNodeType",
    },
    {
      data: { label: "25-isEnergySaving", state: "OFF" },
      id: "25-isEnergySaving",
      position: { x: 600, y: 2500 },
      targetPosition: "Position.Left",
      type: "stateNodeType",
    },
    {
      data: { label: "GnbCuCpFunction-26" },
      id: "GnbCuCpFunction-26",
      position: { x: 400, y: 2550 },
      sourcePosition: "Position.Right",
      targetPosition: "Position.Left",
      type: "customNodeType",
    },
    {
      data: { label: "26-isEnergySaving", state: "OFF" },
      id: "26-isEnergySaving",
      position: { x: 600, y: 2550 },
      targetPosition: "Position.Left",
      type: "stateNodeType",
    },
    {
      data: { label: "GnbCuUpFunction-1", value: "1" },
      id: "GnbCuUpFunction-1",
      position: { x: 400, y: 2600 },
      targetPosition: "Position.Left",
      type: "valueNodeType",
    },
  ],
};
